[project]
authors = ["CKnuchel <christoph.knuchel@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "life"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.2.0.dev2025031105,<26"
python = ">=3.11,<3.13"
pygame = ">=2.6.1,<3"
