name: Mojo CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Magic CLI (Mojo)
        shell: bash
        run: |
          # Install Magic CLI using the official script&#8203;:contentReference[oaicite:2]{index=2}
          curl -ssL https://magic.modular.com/ | bash
          # Source the PATH update script appended by the installer
          source ~/.bashrc
          # Verify installation by checking Magic CLI version&#8203;:contentReference[oaicite:3]{index=3}
          magic --version
          # Add Magic CLI to PATH for subsequent steps
          echo "$HOME/.modular/bin" >> $GITHUB_PATH

      - name: Build with Mojo
        shell: bash
        run: |
          # Use Magic to enter the project environment and build the project
          magic shell -c "mojo build"
