name: Starter Workflow Demo

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl zlib1g-dev libtinfo-dev build-essential 

      - name: Install Magic (Mojo)
        run: |
          curl -ssL https://magic.modular.com/2b3b76c4-24e7-42fc-a68c-8f392ff181bc | bash
          source /home/runner/.bash_profile
          magic --version

      - name: Build
        run: |
          cd life
          magic shell
          mojo build life.🔥  

      - name: Release Binary on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            life/life
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: "Build ${{ github.sha }}"
          body: |
            This is a release for commit ${{ github.sha }}.
            The binary file is `life`.
          draft: false
          prerelease: false
